import Icon from '@/components/Icon';

/**
 * Every AI output on the site carries one of these. A learner should never have
 * to guess whether they are looking at a live model answer, sample data, or a
 * stored snapshot — so the label is part of the result, not a footnote.
 */
const KINDS = {
  demo: {
    label: 'Demo data',
    icon: 'flask',
    className: 'border-amber-300 bg-amber-50 text-amber-800',
    title: 'Sample content shipped with this prompt — no AI provider connected yet.',
  },
  ai: {
    label: 'AI analysis',
    icon: 'sparkles',
    className: 'border-indigo-300 bg-indigo-50 text-indigo-700',
    title: 'Generated by an AI model. Treat it as an informed opinion, not verified fact.',
  },
  snapshot: {
    label: 'Historical snapshot',
    icon: 'clock',
    className: 'border-slate-300 bg-slate-50 text-slate-700',
    title: 'Stored from an earlier run.',
  },
  live: {
    label: 'Live data',
    icon: 'satellite',
    className: 'border-green-300 bg-green-50 text-green-800',
    title: 'Fetched from a live data source.',
  },
};

export default function SourceBadge({ source = 'ai', model, className = '' }) {
  const kind = KINDS[source] || KINDS.ai;
  return (
    <span
      title={kind.title}
      className={`inline-flex items-center gap-1.5 whitespace-nowrap rounded-full border px-2.5 py-1 text-xs font-medium ${kind.className} ${className}`}
    >
      <Icon name={kind.icon} className="h-3 w-3" />
      {kind.label}
      {model && source === 'ai' && <span className="font-normal opacity-70">· {model}</span>}
    </span>
  );
}
