'use client';

import Icon from '@/components/Icon';
import { useLang } from '@/components/LanguageProvider';

/**
 * Every AI output on the site carries one of these. A learner should never have
 * to guess whether they are looking at a live model answer, sample data, or a
 * stored snapshot — so the label is part of the result, not a footnote.
 */
const KINDS = {
  demo: {
    label: { hi: 'Demo data', en: 'Demo data' },
    icon: 'flask',
    className: 'border-amber-300 bg-amber-50 text-amber-800',
    title: {
      hi: 'Is prompt ke saath aaya sample content — abhi koi AI provider connected nahi hai.',
      en: 'Sample content shipped with this prompt — no AI provider connected yet.',
    },
  },
  ai: {
    label: { hi: 'AI analysis', en: 'AI analysis' },
    icon: 'sparkles',
    className: 'border-indigo-300 bg-indigo-50 text-indigo-700',
    title: {
      hi: 'Ek AI model ne banaya hai. Ise ek samajhdaar raay maano, verified fact nahi.',
      en: 'Generated by an AI model. Treat it as an informed opinion, not verified fact.',
    },
  },
  snapshot: {
    label: { hi: 'Purana snapshot', en: 'Historical snapshot' },
    icon: 'clock',
    className: 'border-slate-300 bg-slate-50 text-slate-700',
    title: { hi: 'Pehle ke ek run se store kiya gaya.', en: 'Stored from an earlier run.' },
  },
  live: {
    label: { hi: 'Live data', en: 'Live data' },
    icon: 'satellite',
    className: 'border-green-300 bg-green-50 text-green-800',
    title: { hi: 'Ek live data source se liya gaya.', en: 'Fetched from a live data source.' },
  },
};

export default function SourceBadge({ source = 'ai', model, className = '' }) {
  const { pick } = useLang();
  const kind = KINDS[source] || KINDS.ai;
  return (
    <span
      title={pick(kind.title.hi, kind.title.en)}
      className={`inline-flex items-center gap-1.5 whitespace-nowrap rounded-full border px-2.5 py-1 text-xs font-medium ${kind.className} ${className}`}
    >
      <Icon name={kind.icon} className="h-3 w-3" />
      {pick(kind.label.hi, kind.label.en)}
      {model && source === 'ai' && <span className="font-normal opacity-70">· {model}</span>}
    </span>
  );
}
