import { LEARNER_SYSTEM, inputBlock, jsonInstruction } from './shared';

const SHAPE = {
  platform: 'linkedin | instagram | x | reddit',
  hook: 'the first line, which decides whether anyone reads the rest',
  post: 'the full post text, ready to paste, line breaks included',
  thread: ['for X only: each post of the thread, in order; [] otherwise'],
  slides: [{ title: '…', body: '…' }],
  hashtags: ['#…'],
  notes: 'anything to check before posting — subreddit rules, claims to verify',
};

const PLATFORM_RULES = {
  LinkedIn: [
    'Structure: hook, what you learned, the insight that is not obvious, a practical takeaway,',
    'a short personal reflection, one question to the reader, then hashtags.',
    'Short paragraphs with blank lines between them. No emoji walls, no "I am humbled to announce".',
    'Five hashtags at most. It must read like a person wrote it, not a press release.',
  ],
  Instagram: [
    'Give a caption plus 5-7 carousel slides. Each slide has a title of at most six words and one',
    'or two lines of body. Slide 1 is the hook. The last slide is a call to action.',
    'Up to 12 hashtags, mixed broad and niche.',
  ],
  'X / Twitter': [
    'Give a single standalone post in "post", and a 4-7 post thread in "thread".',
    'Each entry under 270 characters. No thread numbering like 1/7. No hashtag spam — two at most.',
  ],
  Reddit: [
    'Write it as a person asking or sharing, not marketing. Title in "hook", body in "post".',
    'No hashtags. In "notes", remind the reader to read that subreddit’s rules first.',
  ],
};

const template = {
  id: 'social-post',
  title: 'Create a Post',
  short: 'Turn what you learned into a post that sounds like you.',
  description:
    'Generates a ready-to-paste post for LinkedIn, Instagram, X or Reddit from a topic and a few points.',
  category: 'create',
  icon: 'share',
  cta: 'Generate Post',
  version: '1.0',
  status: 'active',
  outputFormat: 'structured',
  resultView: 'post',
  inputs: [
    {
      name: 'platform',
      label: 'Platform',
      type: 'select',
      options: ['LinkedIn', 'Instagram', 'X / Twitter', 'Reddit'],
      default: 'LinkedIn',
      required: true,
    },
    {
      name: 'topic',
      label: 'What is the post about?',
      type: 'text',
      required: true,
      placeholder: 'I learned how the JavaScript event loop works',
    },
    {
      name: 'points',
      label: 'Main points (optional)',
      type: 'textarea',
      placeholder: 'One per line — what surprised you, what clicked, what you built',
    },
    {
      name: 'tone',
      label: 'Tone',
      type: 'select',
      options: ['Professional', 'Personal', 'Storytelling', 'Technical', 'Short and punchy', 'Achievement'],
      default: 'Personal',
    },
    {
      name: 'audience',
      label: 'Who is it for?',
      type: 'text',
      placeholder: 'Other learners, recruiters, senior devs…',
      default: 'Other developers',
    },
  ],
  system: LEARNER_SYSTEM,

  build(inputs, ctx) {
    const rules = PLATFORM_RULES[inputs?.platform] || PLATFORM_RULES.LinkedIn;
    return [
      `Write a ${inputs?.platform || 'LinkedIn'} post for a developer sharing what they learned.`,
      '',
      inputBlock(template, inputs),
      ...(ctx?.achievement
        ? ['', 'Achievement to mention (real, from their account):', JSON.stringify(ctx.achievement)]
        : []),
      '',
      ...rules,
      '',
      'Write in first person as the learner. Claim nothing they did not tell you — no invented job',
      'offers, numbers or company names. Avoid the usual AI tells: no "In today’s fast-paced world",',
      'no "game-changer", no three-word sentence fragments for drama.',
      'Fill only the fields that apply to this platform; leave the others empty.',
      jsonInstruction(SHAPE),
    ].join('\n');
  },

  demo(inputs) {
    const topic = inputs?.topic || 'something new';
    return {
      platform: String(inputs?.platform || 'LinkedIn').toLowerCase(),
      hook: `Sample post about ${topic}.`,
      post: `This is demo output so you can see the layout.\n\nConnect an AI provider under Settings → AI Connections, then hit Regenerate for a real post about ${topic}.`,
      thread: [],
      slides: [],
      hashtags: ['#learning', '#webdev'],
      notes: 'Demo data — not generated by a model.',
    };
  },
};

export default template;
